spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fastform?characterEncoding=utf-8
    username: root
    password: root



mybatis:
  type-aliases-package: com.hzy.fastformadmin.Entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30